
package main;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author Michael
 */
public class ProbabilityPanel extends javax.swing.JPanel {

    private final static int PROGRESS_UPDATE_SPEED = 75;
    private final static int TIME_ESTIMATE_UPDATE_SPEED = 1000;

    JFrame frame;
    ProbabilityCalculator calc;
    Timer progressTimer;
    
    private int timeEstimate;
    private long lastTimeEstimateUpdate;

    /**
     * Creates new form ProbabilityPanel
     */
    public ProbabilityPanel() {
        initComponents();
        calc = new ProbabilityCalculator();
        progressTimer = new Timer(PROGRESS_UPDATE_SPEED, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                progressBar.setValue(calc.getProgress());
                updateText();
                if (!calc.isRunning()) {
                    progressTimer.stop();
                    calculationFinished();
                }
            }
        });
        progressTimer.setRepeats(true);
    }

    public void displaySelf(Component c) {
        if (frame == null) {
            frame = new JFrame("Probabilities");
            frame.add(this);
            frame.pack();
        }
        frame.setLocationRelativeTo(c);
        frame.setVisible(true);
    }

    private void updateText() {
        String text = "";
        double et = calc.getElapsedTime() / 1000.0;
        updateTimeEstimate();
        text += "Time Elapsed: " + et;
        text += "\nEstimated Time: "+timeEstimate;
        text += "\nRoll Combinations Tried: " + calc.getProgress();
        text += "\nOuter Die Number: " + calc.getOuterNumber();
        this.jTextArea1.setText(text);
    }

    private void updateTimeEstimate(){
        if(System.currentTimeMillis()-this.lastTimeEstimateUpdate>TIME_ESTIMATE_UPDATE_SPEED){
            this.timeEstimate = (int)((calc.getElapsedTime()*calc.getProgressTotal()/1000.0)/calc.getProgress());
            this.lastTimeEstimateUpdate = System.currentTimeMillis();
        }
    }
    
    public void calculationFinished() {
        this.beginCalculationButton.setEnabled(true);
        this.calcelCaclulationButton.setEnabled(false);
        progressBar.setValue(0);
        if (calc.didFinish()) {
            //Set the final text
            String text = "";
            text += "Total Computation Time: " + calc.getElapsedTime() / 1000.0;
            text += "\nTotal Toll Combinations: " + calc.getProgressTotal();
            text += "\n+";
            text += "\nPrimes By Level";
            text += "\n+";
            HashMap<Integer, Integer> levels = calc.getPrimesByLevel();
            for (Integer key : levels.keySet()) {
                text += "\nThere are " + levels.get(key) + " rolls for level " + key;
                text += "\nLikelihood: " + ((double) levels.get(key) / calc.combosTriedInSession) * 100 + "\n";
            }
            this.jTextArea1.setText(text);
        } else {
            this.jTextArea1.setText("Calculation Canceled.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        beginCalculationButton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        progressBar = new javax.swing.JProgressBar();
        calcelCaclulationButton = new javax.swing.JButton();

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(2, 2, null, 1));

        jLabel1.setText("Number of die:");

        beginCalculationButton.setText("Begin Calculation");
        beginCalculationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginCalculationButtonActionPerformed(evt);
            }
        });

        jCheckBox1.setText("d8 option");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        calcelCaclulationButton.setText("Cancel Calculation");
        calcelCaclulationButton.setEnabled(false);
        calcelCaclulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcelCaclulationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(beginCalculationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(progressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calcelCaclulationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(beginCalculationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcelCaclulationButton)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void beginCalculationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginCalculationButtonActionPerformed
        beginCalculationButton.setEnabled(false);
        this.calcelCaclulationButton.setEnabled(true);
        calc.setNumDie((int) this.jSpinner1.getValue(), this.jCheckBox1.isSelected());
        progressBar.setMaximum(calc.getProgressTotal());
        calc.calculateProbabilities(true);
        progressTimer.start();
    }//GEN-LAST:event_beginCalculationButtonActionPerformed

    private void calcelCaclulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcelCaclulationButtonActionPerformed
        calc.cancelCalculation();
    }//GEN-LAST:event_calcelCaclulationButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beginCalculationButton;
    private javax.swing.JButton calcelCaclulationButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
